services:
  db:
    container_name: pg_db
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    user: "${UID}:${GID}"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=password
    restart: unless-stopped

  server:
    container_name: node-server
    build:
      context: .
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    ports:
      - '3004:3000'
    volumes:
      - .:/usr/src/app

volumes:
  postgres-data:
